#!/usr/bin/env bash

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --version) version="$2"
    ;;
  esac
  shift
  shift
done

# Download online installer with asc file
wget -O harbor-installer.tgz https://github.com/goharbor/harbor/releases/download/v"$version"/harbor-online-installer-v"$version".tgz
wget -O harbor-installer.tgz.asc https://github.com/goharbor/harbor/releases/download/v"$version"/harbor-online-installer-v"$version".tgz.asc

# Harbor keys
gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 644FF454C0B4115C

# Verify keys
gpg -v --keyserver hkps://keyserver.ubuntu.com --verify harbor-installer.tgz.asc

# Unzip
tar xzvf harbor-installer.tgz
